- CMakeLists.txt
error during C++ benchmarks compilition
fatal: invalid reference: head
CMake Error at /Projects/benchmarks/cppbuild/Release/aeron-prefix/tmp/aeron-gitclone.cmake:75 (message):
Failed to checkout tag: 'head'
CMakeFiles/aeron.dir/build.make:89: recipe for target 'aeron-prefix/src/aeron-stamp/aeron-download' failed
make[2]: *** [aeron-prefix/src/aeron-stamp/aeron-download] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/aeron.dir/all' failed
make[1]: *** [CMakeFiles/aeron.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
OS "Ubuntu 18.04.3 LTS (Bionic Beaver)"
cmake version 3.10.2
```
> [C++]: add origin prefix for GIT_TAG

- scripts/aggregate-results
- src/main/java/uk/co/real_logic/benchmarks/rtt/Configuration.java
- src/main/java/uk/co/real_logic/benchmarks/rtt/LoadTestRig.java
- src/main/java/uk/co/real_logic/benchmarks/rtt/ResultsAggregator.java
- src/main/java/uk/co/real_logic/benchmarks/rtt/RttHistogram.java
- src/test/java/uk/co/real_logic/benchmarks/rtt/ConfigurationTest.java
- src/test/java/uk/co/real_logic/benchmarks/rtt/LoadTestRigTest.java
- src/test/java/uk/co/real_logic/benchmarks/rtt/ResultsAggregatorTest.java
- src/test/java/uk/co/real_logic/benchmarks/rtt/RttHistogramTest.java
- src/test/java/uk/co/real_logic/benchmarks/rtt/aeron/AbstractTest.java
Add two new configuration options:
- `aeron.benchmarks.rtt.outputDirectory` - defines an output directory to store the histogram files. Defaults to `results` in a current directory.
- `aeron.benchmarks.rtt.outputFileNamePrefix` - required property to set file name prefix for the histogram file.
Every run of the `LoadTestRig` will generate a results file in the output directory by adding a unique index to the file. For example if the prefix is set to `my-tests` then the first file will be created with the name `my-tests-0.hdr`, the second as `my-tests-1.hdr` and so on.
There is also an aggregator to combine multiple results into a single file. Aggregator can be either invoked programmatically `uk.co.real_logic.benchmarks.rtt.ResultsAggregator` or via script `aggregate-results`. The …
> [Java] Persist and aggregate bechmark results

- src/main/java/uk/co/real_logic/benchmarks/rtt/Configuration.java
- src/test/java/org/other/benchmark/impl/MessageTransceiverFromAnotherPackage.java
- src/test/java/uk/co/real_logic/benchmarks/rtt/ConfigurationTest.java
- src/test/java/uk/co/real_logic/benchmarks/rtt/LoadTestRigTest.java
- src/test/java/uk/co/real_logic/benchmarks/rtt/aeron/AbstractTest.java
- src/test/java/uk/co/real_logic/benchmarks/rtt/nested/NestedMessageTransceiver.java
Output file name prefix is computed from the configuration values using the following scheme `$className_$numberOfMessages_$batchSize_$messageLength`, where:
- `$className` - is a shortened version of the `MessageTransceiver` class name, i.e. a common prefix `uk.co.real_logic.benchmarks.rtt.` is removed from the fully qualified class name
- `$numberOfMessages` - is the number of messages
- `$batchSize` - is the batch size
- `$messageLength` - is the message length
> [Java] Compute output file name prefix from the configuration

- benchmarks-grpc/src/main/java/uk/co/real_logic/benchmarks/grpc/remote/BlockingMessageTrasceiver.java
- benchmarks-grpc/src/main/java/uk/co/real_logic/benchmarks/grpc/remote/EchoServer.java
- benchmarks-grpc/src/main/java/uk/co/real_logic/benchmarks/grpc/remote/EchoService.java
- benchmarks-grpc/src/main/java/uk/co/real_logic/benchmarks/grpc/remote/GrpcConfig.java
- benchmarks-grpc/src/main/java/uk/co/real_logic/benchmarks/grpc/remote/StreamingMessageTrasceiver.java
- benchmarks-grpc/src/main/proto/grpc_benchmarks.proto
- benchmarks-grpc/src/test/java/uk/co/real_logic/benchmarks/grpc/remote/AbstractGrpcTest.java
- benchmarks-grpc/src/test/java/uk/co/real_logic/benchmarks/grpc/remote/BlockingMessageTrasceiverTest.java
- benchmarks-grpc/src/test/java/uk/co/real_logic/benchmarks/grpc/remote/StreamingMessageTrasceiverTest.java
- build.gradle
- scripts/grpc/blocking-client
- scripts/grpc/server
- scripts/grpc/streaming-client
- settings.gradle
This PR adds a gRPC implementation of the `remote` benchmarks. It follows the same approach as was used for Aeron benchmarks with regards to launch scripts, naming etc.
> [Java] Add remote benchmarks for gRPC

- build.gradle
that's a known issue with grpc https://github.com/grpc/grpc-java/issues/3633
why is not javax.annotation-api see here https://github.com/grpc/grpc-java/issues/6833
> fix java 9+ build

- benchmarks-aeron/src/main/java/uk/co/real_logic/benchmarks/aeron/remote/ClusterNode.java
- benchmarks-api/src/main/java/uk/co/real_logic/benchmarks/remote/LoadTestRig.java
- scripts/aeron/README.md
- scripts/samples/cluster_localhost/client.properties
- scripts/samples/cluster_localhost/cluster.properties
- scripts/samples/cluster_localhost/node0.properties
- scripts/samples/cluster_localhost/node1.properties
- scripts/samples/cluster_localhost/node2.properties
- Changes LoadTestRig and ClusterNode to use `PropertyAction.REPLACE` to allow configuration options to be override where appropriate.
- Tweak the ClusterNode to derive `AeronArchive` settings from the `Archive` and reduce the amount of configuration options required.
- Add sample localhost configuration properties
- Change README.md to reference new sample and change in the ClusterNode.
> Small Configuration Changes and Sample

- scripts/aeron/remote-cluster-benchmarks
- scripts/aeron/remote-echo-benchmarks
- scripts/aeron/remote-live-recording-benchmarks
- scripts/aeron/remote-live-replay-benchmarks
- scripts/grpc/remote-grpc-benchmarks
- scripts/kafka/remote-kafka-benchmarks
- scripts/results-plotter.py
Script that generates graphs for all the aggregated result files in a directory, grouping them by scenario.
The changes in the bash scripts ensure that all the result files have a new common format that makes it easier to parse them.
This requires an improved version of [hdr-plot](https://github.com/BrunoBonacci/hdr-plot) for which the PR is pending.
It is possible to install the [forked version](https://github.com/manuelbernhardt/hdr-plot/tree/additional-features) like so:
```
git clone git@github.com:manuelbernhardt/hdr-plot.git
git checkout additional-features
python3 setup.py install --user
```
> [Python][Bash] Script for plotting benchmark results

- scripts/collect-environment-info
- show only relevant mount points
- when running on AWS EC2, also collect instance IDs, name and volumes
> [Bash] Improving environment collection script

- benchmarks-api/src/main/java/uk/co/real_logic/benchmarks/remote/Configuration.java
- benchmarks-api/src/test/java/uk/co/real_logic/benchmarks/remote/ConfigurationTest.java
- benchmarks-kafka/src/main/java/uk/co/real_logic/benchmarks/kafka/remote/KafkaMessageTransceiver.java
- scripts/aeron/remote-cluster-benchmarks
- scripts/aeron/remote-echo-benchmarks
- scripts/aeron/remote-live-recording-benchmarks
- scripts/aeron/remote-live-replay-benchmarks
- scripts/grpc/remote-grpc-benchmarks
- scripts/kafka/remote-kafka-benchmarks
- scripts/remote-benchmarks-runner
- scripts/results-plotter.py
- introduce `--context` switch for benchmark runner scripts
- generate the archive file name instead of taking it as input
- use `key1=value1^key2=value2` as format for the parameters
- remove distinction between "context" and "normal" parameters
- filters of the results plotter are now AND filters instead of OR filters
- support multiple input directories for the results plotter
> Result processing improvements

- scripts/results-plotter.py
This shows field names (of the grouped fields). It is possible to hide them with the `--hide-field-name` flag.
> [Python] Show field names by default in labels

- scripts/results-plotter.py
Option to hide summary boxes (when plotting a lot of graphs)
> Python: option to hide summaries

- .dockerignore
- Dockerfile
- scripts/collect-environment-info
- scripts/k8s-remote-testing.sh
- scripts/k8s/k8s-benchmark-entrypoint.sh
- scripts/k8s/k8s-benchmark.yml
- scripts/k8s/k8s-test-customisation.yml
- scripts/k8s/kustomization.yml
- scripts/k8s/settings.yml
Adds the following on K8s:
* Gradle caching for the Docker build
* Making `tuned-adm` optional during `collect-environment-info`. Containers won't have this.
* Moving more work into the container, so people don't have to have a local gradle build.
* Prep-work for dynamic test configuration
* Adding `collect-environment-info` output into test results
* Change of execution container to Zulu-17
> feat(CAF-552): Improvements to K8s reports

- scripts/aeron/remote-archive-replay-mdc-benchmarks
- scripts/aeron/remote-cluster-benchmarks
- scripts/aeron/remote-echo-mdc-benchmarks
- scripts/aeron/remote-echo-single-host-benchmarks
Sometimes a benchmark gets stuck and it difficult to figure out based on the logging if this is the case because no timestamps are printed.
This PR adds timestamps to the start of a benchmark run of various benchmarks.
Logging will show something like
> Include the date/time when a run of a benchmark starts.

- build.gradle
Otherwise the following build error is the result
* What went wrong: Could not determine the dependencies of task ':benchmarks-all:shadowJar'.
> Could not resolve all dependencies for configuration ':benchmarks-all:runtimeClasspath'.
> Conflict found for the following module:
- com.google.protobuf:protobuf-java between versions 3.25.5 and 3.25.3
> Add fix for version conflict on protobuf.

- scripts/remote-benchmarks-runner
Adds a 60s timeout to the await_process_start. 
This prevents waiting (hanging) if the process could not be found.
> Fixes hang in await_process_start

- scripts/aeron/remote-archive-replay-mdc-benchmarks
- scripts/aeron/remote-cluster-benchmarks
- scripts/aeron/remote-echo-benchmarks
- scripts/aeron/remote-echo-mdc-benchmarks
- scripts/aeron/remote-echo-single-host-benchmarks
- scripts/aeron/remote-live-recording-benchmarks
- scripts/aeron/remote-live-replay-benchmarks
- scripts/grpc/remote-grpc-benchmarks
- scripts/kafka/remote-kafka-benchmarks
Instead of using a chain of commands using &&, the script is run with -e and the now there is a sequence of commands.
The original code was pretty hard to understand and this should improve maintainability.
> Simplified the remote ipc/cluster/echo benchmark scripts.

- benchmarks-aeron/src/main/java/io/aeron/benchmarks/aeron/AeronUtil.java
This is needed for Sequencer benchmarks because the sequencer benchmark classes will be in a package with a different name.
> Opened up the AeronUtil

- build.gradle
It will not include the version and will have a fixed name.
The inclusion of the version was triggered by this PR:
https://github.com/aeron-io/benchmarks/pull/73
> Fixed naming of benchmark.tar

- scripts/collect-environment-info
With this PR, he topology is also stored in XML format to make it a lot easier to parse.
Especially the topology of the CPU internals with its NUMA nodes, caches, cores etc etc.
> collect-environment-info: Add topology-xml section.

- build.gradle
After the upgrade to gradle 9.0:
https://github.com/aeron-io/benchmarks/commit/a28e2fc7925ae7271dbda2461566ea01637f5655
The file dates and permissions were no longer copied. So e.g. the executable permission was lost on the script files and the benchmarks stopped running.
This PR fixes that (restores the original behavior).
> Fix scripts file attributes

- scripts/aeron/remote-archive-replay-mdc-benchmarks
- scripts/aeron/remote-cluster-benchmarks
- scripts/aeron/remote-echo-benchmarks
- scripts/aeron/remote-echo-mdc-benchmarks
- scripts/aeron/remote-echo-single-host-benchmarks
- scripts/aeron/remote-live-recording-benchmarks
- scripts/aeron/remote-live-replay-benchmarks
Added the OUTPUT_DIR variable to all scripts so that on the 'remote' side, every script knows the directory it can output to.
This is useful when overriding scripts in running with e.g. async-profilers so that the jfr files can be placed in the $OUTPUT_DIR and automatically be downloaded.
> Added OUTPUT_DIR environment var.
